### PR TITLE
Package upgrade and code refactoring

### PR DESCRIPTION
**Pull request by pinguinjkeke**
Hello!

- Added eslint with AirBNB preset.
- Switch from React.PropTypes to separate PropTypes package as is prop types removed from React 16
- Little fixes in Java code.
- Picker doesn't use labels by default.
- Lodash dependency no longer needed.
- Demo project upgraded to latest React Native

### CODE REVIEW

**Comment by pinguinjkeke** [comment]
I cannot contact with repo maintainer. If there will be no response, I'll create another fresh repository. It's okay?

**Comment by avid21** [comment]
sure!

**Comment by pinguinjkeke** [comment]
@avid21 https://github.com/pinguinjkeke/react-native-wheel-datepicker

**Comment by lesliesam** [comment]
Your new repo looks great. I think it is good idea to create a new repo with your new changes. Thank you very much.

**Comment by pinguinjkeke** [comment]
@lesliesam thank you too

**Pull request closed without merging**
