### PR TITLE
Changed createJSModules to support rn 0.47

### PR DESCRIPTION
**Pull request by mcousillas6**
Fixes react native compatibility on android removing the @Override annotation on createJSModules.

Related to #25 but this one supports backwards compatibility.

### CODE REVIEW

**Comment by wildQueequeg** [comment]
@lesliesam Please merge this PR so we don't have to change the module after installing it. Thanks!

**Comment by pinguinjkeke** [comment]
@mcousillas6 https://github.com/pinguinjkeke/react-native-wheel-datepicker/releases/tag/2.1.0

**Comment by rknell** [comment]
Has this been merged yet? I'm the creator of #25 above and just got bitten again and circlejerked back to here.

**Comment by pinguinjkeke** [comment]
@rknell check my repo

**Comment by lesliesam** [comment]
Merged another pull request with the same purpose. So I would close this and thank you very much!

**Pull request closed without merging**
